# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is an application:  KWebTest

HEADERS += browser.h \
           browserview.h \
           kwebtest.h \
           JsRunner.h \
           kwebtestincludes.h \
           testWindow.h 
SOURCES += browser.cpp \
           browserview.cpp \
           kwebtest.cpp \
           main.cpp \
           JsRunner.cpp \
           kwebtestincludes.cpp \
           testwindow.cpp 
TEMPLATE = app
TARGET = KWebTest
INCLUDEPATH += . /usr/include/kde
LIBS += -lkdeui -lkdecore -lkhtml -lkparts -lkio -lkutils
CONFIG += qt release warn_on console 
