#############################################################################
# Makefile for building: KWebTest
# Generated by qmake (1.07a) (Qt 3.3.7) on: Wed Feb 27 23:39:37 2008
# Project:  test.pro
# Template: app
# Command: $(QMAKE) -o Makefile test.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/kde -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lkdeui -lkdecore -lkhtml -lkparts -lkio -lkutils -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = browser.h \
		browserview.h \
		kwebtest.h \
		JsRunner.h \
		kwebtestincludes.h \
		testWindow.h
SOURCES = browser.cpp \
		browserview.cpp \
		kwebtest.cpp \
		main.cpp \
		JsRunner.cpp \
		kwebtestincludes.cpp \
		testwindow.cpp
OBJECTS = browser.o \
		browserview.o \
		kwebtest.o \
		main.o \
		JsRunner.o \
		kwebtestincludes.o \
		testwindow.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_browser.cpp \
		moc_browserview.cpp \
		moc_kwebtest.cpp \
		moc_JsRunner.cpp \
		moc_testWindow.cpp
OBJMOC = moc_browser.o \
		moc_browserview.o \
		moc_kwebtest.o \
		moc_JsRunner.o \
		moc_testWindow.o
DIST	   = test.pro
QMAKE_TARGET = KWebTest
DESTDIR  = 
TARGET   = KWebTest

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: test.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile test.pro
qmake: 
	@$(QMAKE) -o Makefile test.pro

dist: 
	@mkdir -p .tmp/KWebTest && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/KWebTest/ && ( cd `dirname .tmp/KWebTest` && $(TAR) KWebTest.tar KWebTest && $(GZIP) KWebTest.tar ) && $(MOVE) `dirname .tmp/KWebTest`/KWebTest.tar.gz . && $(DEL_FILE) -r .tmp/KWebTest

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

browser.o: browser.cpp kwebtestincludes.h \
		browser.h \
		browserview.h \
		JsRunner.h \
		testWindow.h

browserview.o: browserview.cpp browserview.h \
		JsRunner.h \
		kwebtestincludes.h

kwebtest.o: kwebtest.cpp kwebtest.h \
		kwebtestincludes.h

main.o: main.cpp browser.h \
		teststate.h \
		kwebtestincludes.h \
		JsRunner.h \
		testWindow.h

JsRunner.o: JsRunner.cpp JsRunner.h \
		testWindow.h \
		kwebtestincludes.h

kwebtestincludes.o: kwebtestincludes.cpp kwebtestincludes.h

testwindow.o: testwindow.cpp testWindow.h \
		JsRunner.h \
		browserview.h \
		kwebtestincludes.h

moc_browser.o: moc_browser.cpp  browser.h kwebtestincludes.h \
		JsRunner.h \
		testWindow.h

moc_browserview.o: moc_browserview.cpp  browserview.h kwebtestincludes.h \
		JsRunner.h

moc_kwebtest.o: moc_kwebtest.cpp  kwebtest.h kwebtestincludes.h

moc_JsRunner.o: moc_JsRunner.cpp  JsRunner.h kwebtestincludes.h

moc_testWindow.o: moc_testWindow.cpp  testWindow.h kwebtestincludes.h

moc_browser.cpp: $(MOC) browser.h
	$(MOC) browser.h -o moc_browser.cpp

moc_browserview.cpp: $(MOC) browserview.h
	$(MOC) browserview.h -o moc_browserview.cpp

moc_kwebtest.cpp: $(MOC) kwebtest.h
	$(MOC) kwebtest.h -o moc_kwebtest.cpp

moc_JsRunner.cpp: $(MOC) JsRunner.h
	$(MOC) JsRunner.h -o moc_JsRunner.cpp

moc_testWindow.cpp: $(MOC) testWindow.h
	$(MOC) testWindow.h -o moc_testWindow.cpp

####### Install

install:  

uninstall:  

